# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HARMONICinsight.InsightDocTranslator
PackageVersion: 1.0.8
InstallerType: inno
Scope: machine
ElevationRequirement: elevatesSelf
UpgradeBehavior: install
MinimumOSVersion: 10.0.17763.0
ProductCode: '{00000000-0000-0000-0000-INST00000000}_is1'
AppsAndFeaturesEntries:
- DisplayName: InsightDocTranslator 1.0.8
  Publisher: HARMONIC insight
  ProductCode: '{00000000-0000-0000-0000-INST00000000}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://pub-d1cd1506722c474f89a5ea4df69f744a.r2.dev/InsightDocTranslator_Setup_1.0.8.exe
  InstallerSha256: 5F0E0909061372F339323A9211020A8E41A9506EDBB69A3E9995E2E23C5569C4
ManifestType: installer
ManifestVersion: 1.12.0
