# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HARMONICinsight.InsightDocTranslator
PackageVersion: 1.0.8
InstallerType: zip
NestedInstallerType: inno
NestedInstallerFiles:
- RelativeFilePath: InsightDocTranslator_Setup_1.0.8.exe
Scope: machine
ElevationRequirement: elevatesSelf
UpgradeBehavior: install
MinimumOSVersion: 10.0.17763.0
ProductCode: '{00000000-0000-0000-0000-INST00000000}_is1'
AppsAndFeaturesEntries:
- DisplayName: InsightDocTranslator 1.0.8
  Publisher: HARMONIC insight
  ProductCode: '{00000000-0000-0000-0000-INST00000000}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/HarmonicInsight/cross-releases/releases/download/INST-v1.0.8/InsightDocTranslator_Setup_1.0.8.zip
  InstallerSha256: 8CC894566A0F08109B8E50E509703D040145B8E1B29911FD893195A4EA83E140
ManifestType: installer
ManifestVersion: 1.12.0
